server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:mysql://localhost:3307/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    
#  config:
#    import:
#    - "application_qa.yml"
#    - "application_prod.yml"
#   
#  profiles:
#    active: "qa"
    
#build:
#  version: "3.0"
#
#loans:
#  message: "Welcome to EazyBank loans related local APIs "
#  contactDetails:
#    name: "Amaal Grega - Developer"
#    email: "amaal@eazybank.com"
#  onCallSupport:
#    - (452) 456-2176
#    - (546) 764-8934