server:
  port: 8081
spring:
  # spring cloud config
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
   
management:
  endpoints:
    web:
      exposure:
        include: "*"
        #include: "referesh"  
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true  

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
      
info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"





#  config:
#    import:
#    - "application_qa.yml"
#    - "application_prod.yml"
#  profiles:
#    active:
#    - "qa"
    
#build:
#  version: "3.0"
#  
#accounts:
#  message: "Welcome to EazyBank accounts related local APIs "
#  contactDetails:
#    name: "John Doe - Developer"
#    email: "john@eazybank.com"
#  onCallSupport:
#    - (555) 555-1234
#    - (555) 523-1345